version: "3.8"

services:
  php-docker-template:
    image: php-docker-template-php
    container_name: php-docker-template-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.0.10
        XDEBUG_VERSION: 3.0.4
        COMPOSER_VERSION: 2.1.6
    volumes:
      - type: volume
        source: php-docker-template-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./src/
        target: /var/www/html
      - type: bind
        source: ./docker/php/php.ini-production
        target: /usr/local/etc/php/conf.d/php.ini
        # Override `/usr/local/etc/php-fpm.d/zz-docker.conf` configuration in
        # Docker container.
        # See: https://github.com/docker-library/php/issues/241
      - type: bind
        source: ./docker/php/zzz-docker-override.conf
        target: /usr/local/etc/php-fpm.d/zzz-docker-override.conf
    networks:
      - php-docker-template-network
    env_file: ./docker/php/.env
    ulimits:
      memlock:
        soft: -1
        hard: -1

  php-docker-template-nginx:
    image: php-docker-template-nginx
    container_name: php-docker-template-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: 1.21.1
    volumes:
      - type: volume
        source: php-docker-template-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./docker/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./docker/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "80:80"
    networks:
      - php-docker-template-network
    env_file: ./docker/nginx/.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - php-docker-template-php

networks:
  php-docker-template-network:
    name: php-docker-template-network
    driver: bridge

volumes:
  # For sharing php-fpm socket.
  php-docker-template-fpm-socket:
